#!/usr/bin/env node
/**
 * Bundle one client half into the lazy-CJS script the DSH web client expects.
 *
 * The published DSH client packages are produced by a repository-private
 * `clientBundle` tsdown preset that is not shipped on npm, so a plugin outside
 * that repository has to reproduce the contract itself. The contract is small:
 * a classic script that hands `window.__ModuleLoader__` a factory receiving the
 * platform's frozen module table as `require`, and returning the module exports.
 *
 * Usage: node scripts/build-client.mjs [packageDir=process.cwd()]
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { build } from 'esbuild'

/** Module requests the web shell resolves from its frozen platform table. */
const PLATFORM_MODULES = [
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-store',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
  '@deepseek-ai/dsh-client-ui-dockkit',
]

const packageDir = process.argv[2] === undefined ? process.cwd() : resolve(process.argv[2])
const manifest = JSON.parse(await readFile(join(packageDir, 'package.json'), 'utf8'))
const outfile = resolve(packageDir, 'lib/client.js')

const result = await build({
  absWorkingDir: packageDir,
  entryPoints: ['client/index.tsx'],
  bundle: true,
  write: false,
  format: 'cjs',
  platform: 'browser',
  target: ['chrome120'],
  jsx: 'automatic',
  minify: false,
  legalComments: 'none',
  external: PLATFORM_MODULES,
  logLevel: 'warning',
})

const chunk = result.outputFiles[0]
if (chunk === undefined) throw new Error('esbuild produced no output')
const body = chunk.text.trimEnd()
const indented = body
  .split('\n')
  .map((line) => (line === '' ? line : `\t\t${line}`))
  .join('\n')

const wrapped = `// Generated by scripts/build-client.mjs — do not edit by hand.
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(manifest.name)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
${indented}
\t\treturn module.exports;
\t}
});
`

await mkdir(dirname(outfile), { recursive: true })
await writeFile(outfile, wrapped, 'utf8')
console.log(`built ${outfile} (${Buffer.byteLength(wrapped)} bytes)`)
